name: fizmat_app_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.3.1
  flutter_svg: ^0.23.0+1
  get: ^4.3.8


  cupertino_icons: ^1.0.2
  firebase_core: ^1.19.1
  gsheets: ^0.4.2
  flutter_background_service: ^2.1.3
  html: 0.15.0
  http: ^0.13.4
  firebase_storage: ^10.3.2
  firebase_database: ^9.0.19
  firebase_crashlytics: ^2.8.5
  firebase_messaging: ^12.0.0
  firebase_auth: ^3.4.2
  firebase_analytics: ^9.2.0
  cloud_firestore: ^3.3.0
  shimmer: ^2.0.0
  flutter_linkify: ^5.0.2
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.5
  flutter_native_splash: ^2.2.0+1
  animated_splash_screen: ^1.3.0
  splashscreen: ^1.3.5
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^2.1.0
  bottom_bar_page_transition: ^2.0.0
  curved_navigation_bar: ^1.0.3
  google_sign_in: ^5.4.1
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.2
  google_fonts: ^3.0.1
  flutter_signin_button: ^2.0.0
  animate_icons: ^2.0.0
  fading_edge_scrollview: ^3.0.0
  shaky_animated_listview: ^0.0.5
  flutter_staggered_animations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: "2.0.15"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pics/